$(document).ready(function(){
    $("#designpic").click(function(){
      $("#designpic").slideDown('2000').hide('1000');
      $("#designtxt").show('2000');
    });
    $("#designtxt").click(function(){
      $("#designtxt").slideUp('2000');
      $("#designpic").slideDown('2000');
    });
  });

  $(document).ready(function(){
    $("#developmentpic").click(function(){
      $("#developmentpic").slideDown('2000').hide('1000');
      $("#developmenttxt").show('2000');
    });
    $("#developmenttxt").click(function(){
      $("#developmenttxt").slideUp('2000');
      $("#developmentpic").slideDown('2000');
    });
  });